[versions]
kotlin = "1.7.21"
buildconfig = "3.0.3"
junit = "5.9.0"
junitPlatformConsole = "1.9.0"

[libraries]
# JUnit 5 dependencies
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-platform-console = { group = "org.junit.platform", name = "junit-platform-console", version.ref = "junitPlatformConsole" }


[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
